"use client";

import { useEffect, useState } from "react";
import { PageHeader } from "@/components/ui";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";
import { brDate } from "@/lib/format";
import { AlertTriangle, CheckCircle2, HeartPulse, RefreshCw, ShieldAlert } from "lucide-react";

export default function SaudePage() {
  const [data, setData] = useState<any>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); try { const r = await fetch("/api/health", { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Falha ao carregar saúde."); setData(d); } catch (e: any) { setError(e?.message || "Falha ao carregar saúde."); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  if (loading && !data) return <div className="p-4 md:p-6 md:ml-56 space-y-4"><Skeleton className="h-8 w-56" /><Skeleton className="h-24 rounded-lg" /><Skeleton className="h-64 rounded-lg" /></div>;
  return <div className="p-4 md:p-6 md:ml-56 pb-20 md:pb-6 space-y-4 animate-fade-in"><PageHeader title="Saúde da carteira" subtitle="Risco de churn e próxima ação por cliente." actions={<button onClick={load} className="inline-flex items-center rounded-lg border border-input px-3 py-2 text-xs font-semibold hover:bg-muted"><RefreshCw className="mr-1.5 h-3.5 w-3.5" /> Atualizar</button>} />{error && <div className="rounded-lg border border-red-500/20 bg-red-500/10 px-3 py-2 text-sm text-red-500">{error}</div>}<div className="grid gap-3 md:grid-cols-4"><Stat icon={<HeartPulse className="h-4 w-4 text-primary" />} label="Clientes" value={data?.summary.total || 0} /><Stat icon={<CheckCircle2 className="h-4 w-4 text-emerald-600 dark:text-emerald-400" />} label="Saudáveis" value={data?.summary.healthy || 0} /><Stat icon={<AlertTriangle className="h-4 w-4 text-amber-500" />} label="Atenção" value={data?.summary.attention || 0} /><Stat icon={<ShieldAlert className="h-4 w-4 text-red-500" />} label="Em risco" value={data?.summary.risk || 0} /></div><div className="space-y-3">{data?.clients.map((client: any) => <div key={client.id} className="rounded-lg border border-border/50 bg-card p-4"><div className="flex flex-wrap items-center gap-3"><div className={cn("flex h-12 w-12 items-center justify-center rounded-full text-sm font-bold", client.status === "healthy" ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400" : client.status === "attention" ? "bg-amber-500/10 text-amber-600 dark:text-amber-400" : "bg-red-500/10 text-red-500")}>{client.score}</div><div className="min-w-0 flex-1"><div className="font-semibold">{client.name}</div><div className="text-xs text-muted-foreground">Onboarding: {client.onboarding.done}/{client.onboarding.total} · {client.contract_end_date ? `contrato até ${brDate(client.contract_end_date)}` : "sem vencimento de contrato"}</div></div><span className={cn("rounded-full px-2 py-1 text-[10px] font-bold uppercase", client.status === "healthy" ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400" : client.status === "attention" ? "bg-amber-500/10 text-amber-600 dark:text-amber-400" : "bg-red-500/10 text-red-500")}>{client.status === "healthy" ? "saudável" : client.status === "attention" ? "atenção" : "risco"}</span></div><div className="mt-3 grid gap-2 md:grid-cols-2"><div><div className="mb-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Sinais</div>{client.reasons.map((reason: string) => <div key={reason} className="text-xs text-muted-foreground">• {reason}</div>)}</div><div><div className="mb-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Próxima ação</div>{client.actions.length ? client.actions.map((action: string) => <div key={action} className="text-xs font-medium text-foreground">→ {action}</div>) : <div className="text-xs text-muted-foreground">Nenhuma ação urgente.</div>}</div></div></div>)}</div></div>;
}

function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="rounded-lg border border-border/50 bg-card p-3"><div className="flex items-center gap-2 text-xs text-muted-foreground">{icon}{label}</div><div className="mt-1 text-xl font-bold">{value}</div></div>; }
