"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowUpRight, BarChart3, CalendarDays, CircleDollarSign, RefreshCw, Users, Wallet } from "lucide-react";
import { PageHeader } from "@/components/ui";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { brl } from "@/lib/format";
import { cn } from "@/lib/utils";

type Snapshot = { month: string; active_clients: number; new_clients: number; mrr: number; new_mrr: number; investment: number; cac: number; revenue: number; expenses: number; net_profit: number; renewal_rate: number; variable_revenue: number; churned_clients: number; lost_mrr: number; delinquency_amount: number; warning_clients: number; ltv: number; avg_retention_months: number; avg_time_to_churn_months: number };
type BusinessClient = { id: string; name: string; mrr: number; revenue: number; received: number; overdue: number; contract_end_date: string | null; renewal: string; renewal_days: number | null };
type BusinessData = { current: Snapshot & { clients: BusinessClient[] }; trends: Snapshot[]; error?: string };

const inputClass = "h-9 rounded-lg border border-border bg-transparent px-3 text-sm outline-none focus:ring-1 focus:ring-ring";
const percent = (value: number) => `${Number(value || 0).toFixed(1).replace(".", ",")}%`;
const shown = (value: number | null | undefined) => value == null ? "—" : String(value);
const shownMoney = (value: number | null | undefined) => value == null ? "—" : brl(value);
const shownPercent = (value: number | null | undefined) => value == null ? "—" : percent(value);

export default function NegocioPage() {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const [data, setData] = useState<BusinessData | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); setError(null); try { const response = await fetch(`/api/business?month=${month}`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Falha ao carregar painel."); setData(payload); } catch (reason: any) { setError(reason?.message || "Falha ao carregar painel."); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [month]);
  if (loading && !data) return <div className="p-4 md:p-6 md:ml-56 space-y-4"><Skeleton className="h-8 w-64" /><Skeleton className="h-28 rounded-lg" /><Skeleton className="h-64 rounded-lg" /></div>;
  const current = data?.current;
  return <div className="p-4 md:p-6 md:ml-56 pb-20 md:pb-6 space-y-5 animate-fade-in">
    <PageHeader title="Visão do negócio" subtitle="Indicadores gerados automaticamente pelos lançamentos, clientes, contratos e cobranças." actions={<div className="flex items-center gap-2"><input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className={inputClass} /><Button variant="secondary" size="sm" onClick={load} disabled={loading}><RefreshCw className={cn("mr-1.5 h-3.5 w-3.5", loading && "animate-spin")} /> {loading ? "Atualizando…" : "Atualizar dados"}</Button></div>} />
    {error && <div className="rounded-lg border border-red-500/25 bg-red-500/10 px-3 py-3 text-sm text-red-600 dark:text-red-400"><AlertTriangle className="mr-2 inline h-4 w-4" />{error}<div className="mt-2 text-xs">Execute no Supabase: <code>supabase-migration-business-metrics.sql</code></div></div>}
    {current && <div className="flex flex-col gap-5">
      <Section title="Aquisição & crescimento" tone="blue"><div className="grid gap-3 md:grid-cols-4"><Metric label="Novos clientes" value={shown(current.new_clients)} icon={<Users className="h-4 w-4" />} /><Metric label="MRR novos" value={shownMoney(current.new_mrr)} icon={<ArrowUpRight className="h-4 w-4" />} /><Metric label="Investimento" value={shownMoney(current.investment)} icon={<Wallet className="h-4 w-4" />} /><Metric label="CAC" value={shownMoney(current.cac)} icon={<CircleDollarSign className="h-4 w-4" />} /></div></Section>
      {(current.warning_clients > 0 || current.delinquency_amount > 0) && <div className="rounded-lg border border-amber-500/30 bg-amber-500/10 px-3 py-3 text-sm text-amber-700 dark:text-amber-300"><AlertTriangle className="mr-2 inline h-4 w-4" />{current.warning_clients} cliente(s) com contrato próximo do vencimento e {brl(current.delinquency_amount)} em inadimplência. <Link href="/clientes" className="font-semibold underline">Ver clientes</Link></div>}
      <Section title="Carteira de clientes" tone="blue"><div className="space-y-2">{current.clients.map((client) => <div key={client.id} className="rounded-lg border border-border/50 bg-card p-3"><div className="flex flex-wrap items-center gap-3"><Link href="/clientes" className="min-w-[180px] flex-1 text-sm font-semibold hover:underline">{client.name}</Link><span className="text-xs text-muted-foreground">MRR {brl(client.mrr)}</span><span className="text-xs text-muted-foreground">Receita {brl(client.revenue)}</span><span className="text-xs text-muted-foreground">Recebido {brl(client.received)}</span><span className={cn("rounded-full px-2 py-1 text-[10px] font-semibold", client.overdue > 0 ? "bg-red-500/10 text-red-600 dark:text-red-400" : "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400")}>{client.overdue > 0 ? `Inadimplente · ${brl(client.overdue)}` : "Financeiro em dia"}</span><span className={cn("rounded-full px-2 py-1 text-[10px] font-semibold", client.renewal === "expired" ? "bg-red-500/10 text-red-600 dark:text-red-400" : client.renewal === "in_notice" ? "bg-amber-500/10 text-amber-600 dark:text-amber-400" : client.renewal === "not_configured" ? "bg-muted text-muted-foreground" : "bg-blue-500/10 text-blue-600 dark:text-blue-400")}>{client.renewal === "expired" ? "Renovação vencida" : client.renewal === "in_notice" ? `Renovar em ${client.renewal_days} dias` : client.renewal === "not_configured" ? "Contrato sem data" : "Contrato vigente"}</span></div>{client.contract_end_date && <div className="mt-1 text-[11px] text-muted-foreground">Vencimento do contrato: {client.contract_end_date.split("-").reverse().join("-")}</div>}</div>)}{!current.clients.length && <div className="rounded-lg border border-dashed border-border p-6 text-center text-sm text-muted-foreground">Nenhum cliente ativo cadastrado.</div>}</div></Section>
      <Section title="Pulso do negócio" tone="blue"><div className="grid gap-3 md:grid-cols-5"><Metric label="MRR atual" value={shownMoney(current.mrr)} hint="Base mensal cadastrada" positive /><Metric label="Lucro líquido" value={shownMoney(current.net_profit)} hint={current.net_profit != null && current.revenue ? `Margem: ${percent(current.net_profit / current.revenue * 100)}` : "Margem não informada"} positive={current.net_profit == null || current.net_profit >= 0} /><Metric label="Despesas vs receita" value={current.expenses != null && current.revenue ? percent(current.expenses / current.revenue * 100) : "—"} hint={current.expenses == null ? "Despesas não informadas" : `${brl(current.expenses)} em despesas`} positive={current.revenue == null || current.expenses / current.revenue < 0.6} /><Metric label="Taxa de renovação" value={shownPercent(current.renewal_rate)} hint="Contratos encerrando no mês" positive={current.renewal_rate == null || current.renewal_rate >= 60} /><Metric label="Receita variável" value={shownMoney(current.variable_revenue)} hint={current.variable_revenue != null && current.revenue ? `${percent(current.variable_revenue / current.revenue * 100)} do total` : "Percentual não informado"} /></div></Section>
      <Section title="Estabilidade & risco" tone="amber"><div className="grid gap-3 md:grid-cols-5"><Metric label="Clientes ativos" value={shown(current.active_clients)} positive /><Metric label="Churn" value={current.churned_clients == null ? "—" : `${current.churned_clients} (${current.active_clients ? percent(current.churned_clients / current.active_clients * 100) : "—"})`} positive={current.churned_clients == null || current.churned_clients === 0} /><Metric label="MRR perdido" value={shownMoney(current.lost_mrr)} positive={current.lost_mrr == null || current.lost_mrr === 0} /><Metric label="Inadimplência" value={shownMoney(current.delinquency_amount)} positive={current.delinquency_amount == null || current.delinquency_amount === 0} /><Metric label="Em aviso" value={shown(current.warning_clients)} positive={current.warning_clients == null || current.warning_clients === 0} /></div></Section>
      <Section title="Qualidade da receita" tone="blue"><div className="grid gap-3 md:grid-cols-3"><Metric label="LTV médio" value={shownMoney(current.ltv)} hint="MRR × permanência média" positive /><Metric label="Permanência média" value={current.avg_retention_months == null ? "—" : `${current.avg_retention_months.toFixed(1).replace(".", ",")} meses`} hint="Tempo médio dos clientes ativos" positive /><Metric label="Tempo até churn" value={current.avg_time_to_churn_months == null ? "—" : `${current.avg_time_to_churn_months} meses`} hint="Informe o histórico real" /></div></Section>
      <Section title="Tendências (12 meses)" tone="violet"><div className="grid gap-3 lg:grid-cols-3"><Trend title="Evolução do MRR" data={data?.trends || []} field="mrr" money /><Trend title="Clientes ativos" data={data?.trends || []} field="active_clients" /><Trend title="Churn mensal" data={data?.trends || []} field="churned_clients" /></div><div className="mt-3 rounded-lg border border-dashed border-border p-3 text-xs text-muted-foreground"><CalendarDays className="mr-1 inline h-3.5 w-3.5" /> Estes gráficos são gerados novamente a partir dos lançamentos, clientes e contratos cadastrados.</div></Section>
    </div>}
  </div>;
}

function Section({ title, tone, className = "", children }: { title: string; tone: "blue" | "amber" | "violet"; className?: string; children: React.ReactNode }) { const order = title === "Carteira de clientes" ? "order-10" : title === "Pulso do negócio" ? "order-2" : title === "Estabilidade & risco" ? "order-3" : title === "Qualidade da receita" ? "order-4" : title.startsWith("Tendências") ? "order-5" : "order-1"; return <section className={cn("space-y-3", order, className)}><h2 className="flex items-center gap-2 text-sm font-semibold"><span className={cn("h-2 w-2 rounded-full", tone === "amber" ? "bg-amber-500" : tone === "violet" ? "bg-violet-500" : "bg-blue-500")} />{title}</h2>{children}</section>; }
function Metric({ label, value, hint, icon, positive = true }: { label: string; value: string; hint?: string; icon?: React.ReactNode; positive?: boolean }) { return <div className="rounded-lg border border-border/50 bg-card p-4 shadow-sm"><div className="flex items-center gap-2 text-xs text-muted-foreground">{icon}{label}</div><div className={cn("mt-2 text-xl font-bold", positive ? "text-emerald-600 dark:text-emerald-400" : "text-red-500")}>{value}</div>{hint && <div className="mt-1 text-[11px] text-muted-foreground">{hint}</div>}</div>; }
function Trend({ title, data, field, money }: { title: string; data: Snapshot[]; field: keyof Snapshot; money?: boolean }) { const points = data.map((item) => Number(item[field] || 0)); const max = Math.max(...points, 1); return <div className="rounded-lg border border-border/50 bg-card p-4"><div className="mb-4 flex items-center gap-2 text-xs font-semibold"><BarChart3 className="h-4 w-4 text-primary" />{title}</div><div className="flex h-36 items-end gap-1 border-b border-border/50 px-1">{data.length ? data.map((item, index) => <div key={`${item.month}-${index}`} className="group relative flex h-full flex-1 items-end"><div className={cn("w-full rounded-t bg-primary/70 transition-colors group-hover:bg-primary", field === "churned_clients" && "bg-red-400/70 group-hover:bg-red-500")} style={{ height: `${Math.max(4, Number(item[field] || 0) / max * 100)}%` }} title={`${item.month}: ${money ? brl(Number(item[field] || 0)) : Number(item[field] || 0)}`} /></div>) : <div className="w-full pb-4 text-center text-xs text-muted-foreground">Sem snapshots registrados.</div>}</div><div className="mt-2 flex justify-between text-[10px] text-muted-foreground">{data.slice(-4).map((item) => <span key={item.month}>{item.month.slice(5)}/{item.month.slice(2, 4)}</span>)}</div></div>; }
