"use client";

import { useEffect, useMemo, useState } from "react";
import { Field, Modal, PageHeader } from "@/components/ui";
import { Button } from "@/components/ui/button";
import { BrDateInput } from "@/components/BrDateInput";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";
import { brDate } from "@/lib/format";
import { ArrowDownRight, ArrowUpRight, CircleDollarSign, Plus, RefreshCw, Trash2 } from "lucide-react";

type FinanceData = { month: string; entries: any[]; categories: any[]; clients: any[]; summary: any; dre: any[] };
const inputClass = "w-full h-9 px-3 text-sm rounded-lg border border-border bg-transparent outline-none focus:ring-1 focus:ring-ring";
function money(value: number) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value || 0); }

export default function FinanceiroPage() {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const [data, setData] = useState<FinanceData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [taxRate, setTaxRate] = useState("6");
  const [showForm, setShowForm] = useState(false); const [editingEntryId, setEditingEntryId] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const [kind, setKind] = useState("expense"); const [description, setDescription] = useState(""); const [amount, setAmount] = useState(""); const [dueDate, setDueDate] = useState(`${month}-10`); const [categoryId, setCategoryId] = useState(""); const [clientId, setClientId] = useState(""); const [status, setStatus] = useState("planned");
  const [isRecurring, setIsRecurring] = useState(false); const [recurringDay, setRecurringDay] = useState("10"); const [recurringStart, setRecurringStart] = useState(new Date().toISOString().slice(0, 10));

  async function load() { setLoading(true); setError(null); try { const [fr, rr] = await Promise.all([fetch(`/api/finance?month=${month}`, { cache: "no-store" }), fetch("/api/finance/recurring", { cache: "no-store" })]); const d = await fr.json(); const recurring = await rr.json(); if (!fr.ok) throw new Error(d.error || "Falha ao carregar financeiro."); setData({ ...d, rules: recurring.rules || [] } as FinanceData); } catch (e: any) { setError(e?.message || "Falha ao carregar financeiro."); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [month]);
  useEffect(() => { const saved = window.localStorage.getItem("adsctrl:finance-tax-rate"); if (saved) setTaxRate(saved); }, []);
  function updateTaxRate(value: string) { setTaxRate(value); window.localStorage.setItem("adsctrl:finance-tax-rate", value); }
  const categories = useMemo(() => data?.categories.filter((item) => item.kind === kind) || [], [data, kind]);
  function closeForm() { setShowForm(false); setEditingEntryId(null); setIsRecurring(false); }
  function newEntry() { setEditingEntryId(null); setKind("expense"); setDescription(""); setAmount(""); setDueDate(`${month}-10`); setCategoryId(""); setClientId(""); setStatus("planned"); setIsRecurring(false); setShowForm(true); }
  async function save() { setSaving(true); setError(null); try { const base = { kind, description, amount: Number(amount), due_date: dueDate, category_id: categoryId || null, client_id: clientId || null, status }; const endpoint = isRecurring && !editingEntryId ? "/api/finance/recurring" : "/api/finance"; const body = editingEntryId ? { ...base, id: editingEntryId } : isRecurring ? { ...base, day_of_month: Number(recurringDay), starts_on: recurringStart } : base; const r = await fetch(endpoint, { method: editingEntryId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Falha ao salvar."); closeForm(); await load(); } catch (e: any) { setError(e?.message || "Falha ao salvar."); } finally { setSaving(false); } }
  function editEntry(entry: any) { setEditingEntryId(entry.id); setKind(entry.kind); setDescription(entry.description); setAmount(String(entry.amount)); setDueDate(entry.due_date); setCategoryId(entry.category_id || ""); setClientId(entry.client_id || ""); setStatus(entry.status); setIsRecurring(false); setShowForm(true); }
  function duplicateEntry(entry: any) { setEditingEntryId(null); setKind(entry.kind); setDescription(`${entry.description} (cópia)`); setAmount(String(entry.amount)); setDueDate(entry.due_date); setCategoryId(entry.category_id || ""); setClientId(entry.client_id || ""); setStatus("planned"); setIsRecurring(false); setShowForm(true); setError(null); }
  async function confirmEntry(id: string) { try { const r = await fetch("/api/finance", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status: "confirmed" }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Falha ao confirmar."); await load(); } catch (e: any) { setError(e?.message || "Falha ao confirmar."); } }
  async function deleteEntry(id: string) { if (!window.confirm("Excluir este lançamento?")) return; try { const r = await fetch(`/api/finance?id=${id}`, { method: "DELETE" }); const d = await r.json(); if (!r.ok) throw new Error(d.error); await load(); } catch (e: any) { setError(e?.message || "Falha ao excluir."); } }
  async function deleteRecurring(entry: any) { const ruleId = String(entry.external_id || "").split(":")[0]; if (!ruleId || !window.confirm("Excluir esta receita recorrente e seus próximos lançamentos?")) return; try { const r = await fetch(`/api/finance/recurring?id=${ruleId}`, { method: "DELETE" }); const d = await r.json(); if (!r.ok) throw new Error(d.error); await load(); } catch (e: any) { setError(e?.message || "Falha ao excluir recorrência."); } }
  if (loading && !data) return <div className="p-4 md:p-6 md:ml-56 space-y-4"><Skeleton className="h-8 w-48" /><Skeleton className="h-28 rounded-lg" /><Skeleton className="h-64 rounded-lg" /></div>;
  const summary = data?.summary || {};
  const estimatedTax = Math.max(0, Number(summary.revenue || 0) * Math.max(0, Number(taxRate || 0)) / 100);
  const resultAfterTax = Number(summary.result || 0) - estimatedTax;
  return <div className="p-4 md:p-6 md:ml-56 pb-20 md:pb-6 space-y-4 animate-fade-in">
    <PageHeader title="Financeiro" subtitle="Fluxo de caixa, contas a receber e DRE operacional da agência." actions={<div className="flex items-center gap-2"><input type="month" value={month} onChange={(e) => setMonth(e.target.value)} className={cn(inputClass, "w-auto")} /><Button variant="secondary" size="sm" onClick={load}><RefreshCw className="h-3.5 w-3.5 mr-1" /> Atualizar</Button><Button size="sm" onClick={newEntry}><Plus className="h-3.5 w-3.5 mr-1" /> Lançamento</Button></div>} />
    {error && <div className="rounded-lg border border-red-500/20 bg-red-500/10 px-3 py-2 text-sm text-red-500">{error}</div>}
    <div className="grid gap-3 md:grid-cols-5"><Metric label="Receita prevista" value={money(summary.revenue)} icon={<ArrowUpRight className="h-4 w-4 text-emerald-600" />} /><Metric label="Despesas" value={money(summary.expenses)} icon={<ArrowDownRight className="h-4 w-4 text-red-500" />} /><Metric label="Resultado realizado" value={money(summary.result)} icon={<CircleDollarSign className="h-4 w-4 text-primary" />} tone={summary.result >= 0 ? "text-emerald-600" : "text-red-500"} /><Metric label="Imposto estimado" value={money(estimatedTax)} icon={<span className="text-amber-500">%</span>} tone="text-amber-600" /><Metric label="Resultado após imposto" value={money(resultAfterTax)} icon={<CircleDollarSign className="h-4 w-4 text-primary" />} tone={resultAfterTax >= 0 ? "text-emerald-600" : "text-red-500"} /></div>
    <div className="flex flex-wrap items-center gap-3 rounded-lg border border-border/50 bg-card px-3 py-2 text-xs"><span className="font-semibold">Alíquota estimada sobre a receita prevista:</span><input value={taxRate} onChange={(e) => updateTaxRate(e.target.value)} type="number" min="0" max="100" step="0.1" className="h-8 w-20 rounded-md border border-input bg-transparent px-2 text-right outline-none focus:ring-1 focus:ring-ring" /><span className="text-muted-foreground">% · apenas uma estimativa gerencial; não substitui o cálculo contábil.</span></div>
    {showForm && <Modal title={editingEntryId ? "Editar lançamento" : "Novo lançamento"} onClose={closeForm} wide><div className="space-y-3"><p className="text-xs text-muted-foreground">Cadastre o lançamento e, se quiser, transforme receita ou despesa em recorrência no mesmo formulário.</p><div className="grid gap-3 md:grid-cols-3"><Field label="Tipo"><select value={kind} disabled={!!editingEntryId} onChange={(e) => { setKind(e.target.value); setCategoryId(""); }} className={inputClass}><option value="expense">Despesa</option><option value="revenue">Receita</option></select></Field><Field label="Descrição"><input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Ex.: Mensalidade Cliente X" className={inputClass} /></Field><Field label="Valor"><input value={amount} onChange={(e) => setAmount(e.target.value)} type="number" min="0.01" step="0.01" className={inputClass} /></Field><Field label="Vencimento"><BrDateInput value={dueDate} onChange={setDueDate} className={inputClass} /><span className="text-[11px] text-muted-foreground">Na recorrência, é usado o dia do mês.</span></Field><Field label="Categoria"><select value={categoryId} onChange={(e) => setCategoryId(e.target.value)} className={inputClass}><option value="">Sem categoria</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Cliente"><select value={clientId} onChange={(e) => setClientId(e.target.value)} className={inputClass}><option value="">Agência / sem cliente</option>{data?.clients.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div>{!editingEntryId && <div className="rounded-lg border border-emerald-500/25 bg-emerald-500/5 p-3 space-y-3"><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={isRecurring} onChange={(e) => setIsRecurring(e.target.checked)} /> Cadastrar como {kind === "expense" ? "despesa" : "receita"} recorrente</label>{isRecurring && <div className="grid gap-3 md:grid-cols-2"><Field label="Dia da cobrança"><input value={recurringDay} onChange={(e) => setRecurringDay(e.target.value)} type="number" min="1" max="28" className={inputClass} /></Field><Field label="Início"><BrDateInput value={recurringStart} onChange={setRecurringStart} className={inputClass} /></Field></div>}</div>}<div className="flex items-center gap-2"><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={status === "confirmed"} onChange={(e) => setStatus(e.target.checked ? "confirmed" : "planned")} /> já foi pago/recebido</label><Button variant="secondary" className="ml-auto" size="sm" onClick={closeForm}>Cancelar</Button><Button size="sm" onClick={save} disabled={saving || !description || !amount}>{saving ? "Salvando…" : editingEntryId ? "Salvar alterações" : "Salvar lançamento"}</Button></div></div></Modal>}
    <div className="grid gap-4 lg:grid-cols-[1.3fr_1fr]"><section className="rounded-lg border border-border/50 bg-card p-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-sm font-semibold">Lançamentos de {month}</h2><p className="text-xs text-muted-foreground">Receitas recorrentes aparecem integradas ao lançamento do mês.</p></div><span className="text-xs text-muted-foreground">{data?.entries.length || 0} registros</span></div><div className="space-y-2">{data?.entries.map((entry) => <div key={entry.id} className="flex flex-wrap items-center gap-3 rounded-lg border border-border/40 px-3 py-2"><span className={cn("h-2 w-2 rounded-full", entry.kind === "revenue" ? "bg-emerald-500" : "bg-red-500")} /><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{entry.description}</div><div className="text-[11px] text-muted-foreground">{entry.clients?.name || "Agência"} · {entry.financial_categories?.name || "Sem categoria"} · vence {brDate(entry.due_date)}{entry.source === "recurring" ? " · recorrente" : ""}</div></div><span className={cn("text-sm font-semibold", entry.kind === "revenue" ? "text-emerald-600" : "text-red-500")}>{entry.kind === "revenue" ? "+" : "-"}{money(Number(entry.amount))}</span><div className="flex items-center gap-1"><button onClick={() => editEntry(entry)} className="rounded border border-input px-2 py-1 text-[10px] font-semibold hover:bg-muted">Editar</button><button onClick={() => duplicateEntry(entry)} className="rounded border border-input px-2 py-1 text-[10px] font-semibold hover:bg-muted">Duplicar</button>{entry.status === "planned" ? <button onClick={() => confirmEntry(entry.id)} className="rounded border border-emerald-500/30 px-2 py-1 text-[10px] font-semibold text-emerald-600 hover:bg-emerald-500/10">Confirmar</button> : <span className="px-1 text-[10px] text-muted-foreground">confirmado</span>}<button onClick={() => entry.source === "recurring" ? deleteRecurring(entry) : deleteEntry(entry.id)} className="rounded border border-red-500/20 p-1 text-red-500 hover:bg-red-500/10" title={entry.source === "recurring" ? "Excluir recorrência" : "Excluir lançamento"}><Trash2 className="h-3 w-3" /></button></div></div>)}{!data?.entries.length && <div className="py-8 text-center text-sm text-muted-foreground">Nenhum lançamento neste mês.</div>}</div></section><section className="rounded-lg border border-border/50 bg-card p-4"><h2 className="text-sm font-semibold">DRE por categoria</h2><p className="mb-3 text-xs text-muted-foreground">Visão gerencial do mês selecionado.</p><div className="space-y-2">{data?.dre.map((item) => <div key={item.name} className="flex items-center gap-2 border-b border-border/30 pb-2 text-xs"><span className="flex-1">{item.name}</span>{item.revenue > 0 && <span className="text-emerald-600">+{money(item.revenue)}</span>}{item.expenses > 0 && <span className="text-red-500">-{money(item.expenses)}</span>}</div>)}</div></section></div>
  </div>;
}
function Metric({ label, value, icon, tone = "" }: { label: string; value: string; icon: React.ReactNode; tone?: string }) { return <div className="rounded-lg border border-border/50 bg-card p-3"><div className="flex items-center gap-2 text-xs text-muted-foreground">{icon}{label}</div><div className={cn("mt-1 text-lg font-bold", tone)}>{value}</div></div>; }
